### ISSUE TITLE
Tiny font on 4.0.0 release

### ISSUE THREAD

**Issue by sonjoonho** [tom-james-watson/Emote#109]
On the latest Snap release, all the emojis look tiny. I think this is because the `FONTCONFIG` workaround was remove in https://github.com/tom-james-watson/Emote/pull/96/files#diff-9636b5b799374fc956ab1e6d462a5051b62fd7404bb45aa6e63580d0e005f73fR13-R16. Restoring these lines appears to fix the issue.

![image](https://github.com/tom-james-watson/Emote/assets/20669173/ef1edc22-cceb-4b0f-9613-478a152eec3b)

**Comment by tom-james-watson** [comment]
Putting those lines back in the script reintroduces this issue for me: https://github.com/tom-james-watson/Emote/pull/96#issuecomment-1597080206.

**Comment by sonjoonho** [comment]
Ha that's fun. Okay, I'll see if there's something else we can do.

**Comment by tom-james-watson** [comment]
I'll try and check on some other machines today

**Comment by tom-james-watson** [comment]
What distro are you on? I'm testing on debian 12. I have access to ubuntu 22.04 too.

**Comment by tom-james-watson** [comment]
Just tested on a Fedora 38 VM and both snap and flatpak versions work fine with no obvious issues. Are you using a Wayland or an X11 session?

**Comment by andrewbrey** [comment]
I just upgraded from `3.0.3` to `4.0.0` of my `snap` build and I too have the small font size issue. I'm on `PopOS 22.04` with `Gnome 42` and `X11`. I installed 

![image](https://github.com/tom-james-watson/Emote/assets/34140052/8004307c-14e2-4b20-a7d7-9eae352a077d)

I don't know if this is related, but in case it is, I noticed that in my "about" screen it's indicated that this is a "dev build" which was unexpected given that I installed using `snap install emote` (and I did not specify any specific "dev" channel).

![image](https://github.com/tom-james-watson/Emote/assets/34140052/71b8b407-71ac-4b70-accf-8924fb4f17d1)

**Comment by tom-james-watson** [comment]
The about thing is a separate bug (https://github.com/tom-james-watson/Emote/issues/111).

Do you see the tiny fonts if you try the flatpak version, if you're willing to test that out?

**Comment by andrewbrey** [comment]
> The about thing is a separate bug (https://github.com/tom-james-watson/Emote/issues/111).

Gotcha - thanks!

> Do you see the tiny fonts if you try the flatpak version, if you're willing to test that out?

I just tried the flatpak version and it installs fine, but for me I can't actually get the window to show up, and checking `journalctl` I see the following output:

```
Jun 20 10:06:52 poppy emote_emote.desktop[9414]: Traceback (most recent call last):
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/__init__.py", line 88, in handle_accelerator
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/__init__.py", line 103, in create_picker_window
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/picker.py", line 54, in __init__
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/picker.py", line 85, in init_header
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/picker.py", line 143, in init_skintone_button
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/snap/emote/20/lib/python3.10/site-packages/emote/user_data.py", line 130, in load_skintone_index
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/usr/lib/python3.10/shelve.py", line 243, in open
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:     return DbfilenameShelf(filename, flag, protocol, writeback)
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/usr/lib/python3.10/shelve.py", line 227, in __init__
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:   File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
Jun 20 10:06:52 poppy emote_emote.desktop[9414]:     return mod.open(file, flag, mode)
Jun 20 10:06:52 poppy emote_emote.desktop[9414]: _dbm.error: [Errno 2] No such file or directory: '/home/me/snap/emote/20/.local/share/Emote/user_data'
```

**Comment by tom-james-watson** [comment]
Moved flatpak error to https://github.com/tom-james-watson/Emote/issues/112.

**Comment by tom-james-watson** [comment]
I have just tested on a separate Ubuntu 22.04 machine and confirm that I do see this with the snap version, but not the flatpak version.

@andrewbrey also says in https://github.com/tom-james-watson/Emote/issues/112 that the flatpak version doesn't have this issue.

**Comment by andrewbrey** [comment]
*off topic** - just as color commentary, this is not the first time I've encountered funny font issues with snaps ( for example https://github.com/beekeeper-studio/beekeeper-studio/issues/695 ) and I've found each time that just switching to another format (flatpak, appimage, etc) just tends to work better with respect to fonts. Bummer that it's a persistent pain point with snap builds of applications 😟

**Comment by tom-james-watson** [comment]
Can confirm this fix breaks the app both on debian 12 and fedora 38, but fixes Ubuntu 22.04. I wonder if it's specifically a problem with ubuntu derivatives.

**Comment by tom-james-watson** [comment]
I've just pushed a new snap version that attempts to fix this issue by applying @sonjoonho's font workaround, but only if the system is detected as being a ubuntu-derivative - https://github.com/tom-james-watson/Emote/commit/a6abad4193ac00aa4b2fe8c96659fc2491dc18a9.

This is a pretty shit workaround that will probably break, but as far as I can tell this should fix the issue on the systems we have reports on, without breaking it on the systems we know the fix breaks things on.

Can you please refresh your snap installation and check whether it now displays with normal fonts?

**Comment by sonjoonho** [comment]
Thanks Tom! I can confirm that this works on my Ubuntu installation. The need for the workaround is pretty annoying, but from a little bit of Googling it looks like fonts are just a bit of a mess with Snaps.

**Comment by tom-james-watson** [comment]
@supersandro2000 - I can't reply inline to the comment you made on https://github.com/tom-james-watson/Emote/commit/a6abad4193ac00aa4b2fe8c96659fc2491dc18a9. Unfortunately `/etc/os-release` when running inside the snap returns stuff about Ubuntu Core, not the actual system values. You can explore a bit what is possible if you do `snap run --shell emote` - that drops you into the same environment that script will run in.

**Comment by tom-james-watson** [comment]
If you can find some way of extending the check to exempt nixos then let me know.

**Comment by SuperSandro2000** [comment]
I don't have snap on my machine so I can't really test it but it should be possible to just grep case insensitive for ubuntu or something. /etc/lsb-release should exist on many many distros and just relying on that is not a very good idea.

**Comment by tom-james-watson** [comment]
Looks like this also breaks Ubuntu 23.04. Opening a new issue: https://github.com/tom-james-watson/Emote/issues/115
