### ISSUE TITLE
Flatpak can fail to run with error about db path

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/Emote#112]
https://github.com/tom-james-watson/Emote/issues/109#issuecomment-1599191132

**Comment by tom-james-watson** [comment]
FYI @vemonet another user has seen this happen. (We saw this in dev but couldn't recreate).

**Comment by tom-james-watson** [comment]
@andrewbrey - there's a possibility this is to do with switching from snap to flatpak. Can you confirm that emote is completely closed before trying to run the flatpak, e.g. `killall emote`.

@vemonet - was there anything else you did when you saw this, do you remember?

**Comment by andrewbrey** [comment]
I just wanted to highlight from my comment that I tested the flatpak after already having had the snap previously, and it _seemed_ like the flatpak launch process was loading snap files (which were partially/fully deleted when I ran deleted the snap prior to trying the flatpak)

**Comment by andrewbrey** [comment]
@tom-james-watson that is exactly what was happening, and after ensuring that no emote process was running and that i fully removed both any snap and flatpak installs, i re-installed with flatpak and everything is working correctly (including font sizing):

![image](https://github.com/tom-james-watson/Emote/assets/34140052/8fa1b918-60ec-46af-8536-a755dc0cb3d6)

**Comment by tom-james-watson** [comment]
Yeah I actually just went through this process on another machine and managed to recreate the issue. Killing the existing emote snap process does fix it :+1:
