### ISSUE TITLE
Fonts broken with font workaround on some distros

### ISSUE THREAD

**Issue by Prodeguerriero** [tom-james-watson/Emote#115]
Hi there,

I have just updated to 4.0.1 via Snap on Ubuntu 23.04 with Gnome 44.1, and this is what the Emote UI looks now when invoked:

![Screenshot_2023-06-22_00-34](https://github.com/tom-james-watson/Emote/assets/15149858/07170460-a9e8-4e9e-91ce-e18e983309bd)

If I run `emote` in the terminal, I see the following message: `Running on an Ubuntu-derived system, trying to fix font issue.`

No idea what went wrong here :sweat_smile:

**Comment by tom-james-watson** [comment]
This is caused by a workaround that was applied to fix a seperate big: https://github.com/tom-james-watson/Emote/issues/109.

We need to work out exactly which distros and releases need that fix and only apply it on those...

As a workaround, you should be able to use the flatpak version, which doesn't have this issue.

**Comment by floviolleau** [comment]
Hi,

same as #122

**Comment by Prodeguerriero** [comment]
@floviolleau 

Well, technically #122 is a duplicate of this one, not the other way around. ;)

**Comment by tom-james-watson** [comment]
At the moment unfortunately I don't know how to resolve this or why it happens. As I say, the flatpak version should not suffer from this issue. I'm tempted to unpublish the snap version if this can't be resolved.

**Comment by tom-james-watson** [comment]
I don't think that message is a fatal error. Are you sure it doesn't open if you run the command again whilst keeping the first open? If you're using wayland then you'll need to update your hotkey command: https://github.com/tom-james-watson/Emote/wiki/Hotkey-In-Wayland.

**Comment by floviolleau** [comment]
Sure. Nothing opens with this command.
I'm using Xorg because Wayland is too buggy especially with screen sharing

**Comment by tom-james-watson** [comment]
Just running that command once will not open anything. All that would do is start the daemon. You'd need to run the app again to actually activate the picker. Let's not derail this thread though. If you're still having problems, please open a new issue 🙏.

**Comment by larowlan** [comment]
Not sure if this is relevant, but I'm experiencing this issue

prepare-launch has this

```
if [ -f /etc/lsb-release ]; then
  echo "Running on an Ubuntu-derived system, trying to fix font issue."
  export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
  export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
else
  echo "Not running on an Ubuntu-derived system. Nothing to do."
fi
```

but inside my snap I have this

```
ls -l ./emote/23/etc/fonts
total 3
drwxr-xr-x 2 root root 1467 Jun 21 04:47 conf.avail
drwxr-xr-x 2 root root  994 Jun 21 04:47 conf.d
-rw-r--r-- 1 root root 2808 Mar 23  2022 fonts.conf

```

i.e. I have conf.d not config.d

**Comment by soygabimoreno** [comment]
Hi! :slightly_smiling_face: 
Could I help by giving you some logs or something?
If yes, what could I add?

BTW, this is my computer config:
![image](https://github.com/tom-james-watson/Emote/assets/1880789/cb4e13ff-a656-4a3b-bd8c-8d7c213e6fdc)
![image](https://github.com/tom-james-watson/Emote/assets/1880789/5e5ca687-182d-48f5-b45b-09df0a8fd6bc)
![image](https://github.com/tom-james-watson/Emote/assets/1880789/5d16a70c-a2cd-4723-ad49-999d1a16317d)


Thank you!

**Comment by tom-james-watson** [comment]
Seems to also be happening on Ubuntu 23.04: https://github.com/tom-james-watson/Emote/issues/134.

**Comment by tom-james-watson** [comment]
As of version 4.1.0 of the snap, this should be fixed. Many thanks to @dobicinaitis for working out the fix (https://github.com/tom-james-watson/Emote/pull/135)!!

**Comment by soygabimoreno** [comment]
It's working as expected! :100: 

Thank you so much for the fix, @dobicinaitis.

![image](https://github.com/tom-james-watson/Emote/assets/1880789/ac2ed2e8-b7a6-4325-936b-58a8148809f4)
