### ISSUE TITLE
Emote using flatpack does not open on Linux mint 21.1

### ISSUE THREAD

**Issue by kevocodes** [tom-james-watson/Emote#116]
I recently installed emote using flatpack, when I download the flatpack package it is installed through the linux mint native software manager and when the package is already installed and I want to open it, it just won't open.

even if i try to open emote using the terminal it doesn't recognize the command

![ksnip_20230622-225704](https://github.com/tom-james-watson/Emote/assets/62626446/a93b22d4-285f-4b48-8005-123cc7ede2b9)

**Comment by tom-james-watson** [comment]
To run a flatpak, you need to do `flatpak run com.tomjwatson.Emote`. Try that and paste the output here.

**Comment by kevocodes** [comment]
This is the output when running ```flatpak run com.tomjwatson.Emote```:

![ksnip_20230626-153137](https://github.com/tom-james-watson/Emote/assets/62626446/3227f41a-0ec0-4654-99b6-8c0483440c61)

**Comment by tom-james-watson** [comment]
Merging with https://github.com/tom-james-watson/Emote/issues/117
