### ISSUE TITLE
[Discussion] Can we implement, the auto pasting feature?

### ISSUE THREAD

**Issue by sarojregmi200** [tom-james-watson/Emote#123]
I was searching for the `win + .` alternative in linux. And I found this repo. It's great I have completed setting it up with the shortcuts it works fine but when I search for any emote and then hit enter the window closes and the emote gets copied to my clipboard.
It is not possible to directly paste the emote where the cursor is active I mean where we were typing, rather than copy pasting the emote it is way faster and easier that way.

Is this feature available in this application?
If not can we have someone build this feature, If everyone agrees?
I am ready to see if I can do it, And I wanted to know the needs first to implement this feature.

Thank you.

**Comment by tom-james-watson** [comment]
Unfortunately there's no known way of doing an auto-paste on Wayland at this point that doesn't require the user to change the permissions of some system files, which is something we can't recommend.
