### ISSUE TITLE
How to make emoji list display bigger?

### ISSUE THREAD

**Issue by laraws** [tom-james-watson/Emote#124]
Compared to Ubuntu Characters emoji, the Emote emoji display is so small. How can I make the emoji list display bigger?

This is Emote:
![image](https://github.com/tom-james-watson/Emote/assets/40230381/43981cd4-eb9a-4fb6-94fc-26e13f6de07e)

This is Ubuntu Characters:
![image](https://github.com/tom-james-watson/Emote/assets/40230381/fb04d202-e2b7-4eec-b501-88ceb0b0c190)

**Comment by tom-james-watson** [comment]
It's not possible and I don't think it's something that would ever be supported, I'm afraid.
