### ISSUE TITLE
Tray icon?

### ISSUE THREAD

**Issue by mxmilkiib** [tom-james-watson/Emote#125]
It would be handy to have the option for a tray icon to click on to get the dialog box up.

**Comment by tom-james-watson** [comment]
I don't think this is something I'd want to add support for to be honest. The app icon already lets you do the same thing. Maybe if a lot of people ask for this we can reconsider.

**Comment by waldyrious** [comment]
> Maybe if a lot of people ask for this we can reconsider.

I for one would like this too.

**Comment by tom-james-watson** [comment]
I don't know AwesomeWM but when you install Emote you should get an entry in your application list. That entry can be added to the dock in gnome, kde etc and clicking it if Emote is already running will open the picker.

**Comment by mxmilkiib** [comment]
Not all Linux desktop setups have an icon based app launcher visible all of the time. I start my apps using hotkeys or from a hotkey triggered Rofi menu. 

![image](https://github.com/tom-james-watson/Emote/assets/108225/b3b757fe-394b-44f6-9cea-67b14dd37807)

**Comment by waldyrious** [comment]
> That entry can be added to the dock in gnome, kde etc

I am actually not able to pin the icon to the dock. The icon appears there when I invoke Emote, but as soon as I try to right-click the dock icon, the app loses focus and closes, and thus the icon disappears along with its context menu. I'm on Ubuntu if that helps.

**Comment by tom-james-watson** [comment]
On Gnome press "Show Applications" and drag the app to the dock from the app list.

**Comment by waldyrious** [comment]
Oh, I feel silly now. Thanks for the tip, and sorry for the noise!
