### ISSUE TITLE
Automatically paste emoji to current window on select

### ISSUE THREAD

**Issue by tomsquest** [tom-james-watson/Emote#13]
This feature would speed-up the workflow:
- find an emoji
- click/select
- the emoji is copied into the "parent" window

This feature is the same as CopyQ "Paste to current window"

![image](https://user-images.githubusercontent.com/365778/95180567-71d89000-07c2-11eb-85a7-694bf26a8750.png)

**Comment by tom-james-watson** [comment]
Yeah this is how I want the app to work, but I was not able to find a reliable way of doing this.

If someone knows how to achieve that with GTK / system calls / python libraries, please let me know.

**Comment by tom-james-watson** [comment]
I've worked out how to get this working reliably. It would be awesome if some people could test out the branch with the implementation to confirm that it is working :pray:: https://github.com/tom-james-watson/Emote/pull/26

**Comment by tomsquest** [comment]
v1.4.0 (snap) working fine here in Kubuntu 20.04 : paste in done on emoji select. :+1:
