### ISSUE TITLE
Force Emote to change keyboard shortcut

### ISSUE THREAD

**Issue by stdedos** [tom-james-watson/Emote#130]
Hello there!

I was wondering - would https://github.com/tom-james-watson/Emote/commit/054bbb54862afa5c10f3403fd330dce620b943b4 solve the issue with changing the triggering keyboard shortcut?

On the first flatpak-install, I tried to change the shortcut to `Ctrl+Shift+E` (interferes with bash's `Ctrl+Alt+E` :: expand-alias).

No matter how many times I killed it, it blatantly refused to re-set the shortcut to `Ctrl+Shift+E`. However, it did release the `Ctrl+Alt+E` one.
I needed to restart the system for that to work 😕

**Comment by tom-james-watson** [comment]
Honestly I'm not sure I follow. I don't really understand how the flatpak autostart fix would have anything to do with keyboard shortcuts though, no.

**Comment by stdedos** [comment]
Idk - I connected "restarts" with re-setting the shortcut 😅 

Thank you for your fast response!
