### ISSUE TITLE
Feature request: Favorites, symbols, + a few suggestions + Chrome issue.

### ISSUE THREAD

**Issue by nightgolfer** [tom-james-watson/Emote#137]
Absolutely love Emote after having tried all the other options I could find. Can report that it works almost flawlessly on Fedora 39 / KDE Plasma 5.27.8 / X11, and is very responsive 👍️

As a new Linux user (converted EOL Chromebook) and coming from MacOS, I'd like to suggest a few features from the built-in MacOS emoji and symbol picker ([Character Viewer](https://support.apple.com/en-gb/guide/mac-help/mchlp1560/mac) / CV) that might enhance Emote, as well as a few UI/UX suggestions.

**(EDIT**: The various feature requests and issues in the original post have been split into separate Issues)

**FAVORITES**: In addition to Recently Used emoji, I love CV's option of adding Favorites. They may not be the ones I use the most, but I have a small, curated list of the emoji (and symbols, see below) that are important to me. This gives me ultra fast access to a selection of emoji from across all categories, and they are always exactly where I left them, unlike Recently Used which changes constantly. With Emote's "Stack" feature, I can even add multiple of my Faves to an input area at once, and I don't have to perform multiple searches to find them.

- Implementation suggestion:
    - Enable/disable Favorites in Settings. It might not be for everyone. The simplest solution might be a Hide Favorites option in Settings. 
    - When enabled (not Hidden), Favorites show up as an extra area at the bottom of the Emote window, below the Preview area.
    - Favorites area expands to hold the users Favorites, one row at a time (maybe with a max row count like 3 or 4, with scroll appearing for 4-row overflow). This eliminates unnecessary window size bloat.
    - When an emoji is added to Favorites, the Favorites Area appears if not already visible, and can be Hidden again from Settings.
    - When opening Emote, the cursor currently starts in the search field. Arrows Up, Left and Right do nothing, Arrow Down moves the "selection" to the emoji area, selecting the first emoji. I propose pressing Arrow Up moves the selection to the Favorites area at the bottom of the window, effectively making arrow selection "wrap" from top to bottom.
    - As Favorites are hand-picked by the user, the Favorites area should respect the users sorting, and allow re-ordering emoji.
    - Issue: How to add an emoji to Favorites? 
        - Currently, left clicking an emoji pastes it into the previous app, and closes Emote. 
        - A long click/press does the same (meaning dragging is also a no-go). 
        - Right clicking adds the emoji to the "stack". 
        - I'm on a laptop, so middle click is very dependent on individual user setup and hardware (also true for some desktop computers/input devices). 
        - That leaves a keyboard shortcut for adding Favorites. CTRL+F is already used for Focus Search Field. ALT+F could be a candidate.
    - Issue: How to allow re-ordering of Favorites in Favorites area+
        - The most intuitive way would be dragging to re-order, but long-pressing is currently registered as a click (see above), so dragging also doesn't work.
        - Either allow dragging in Favorites area, or add a Re-order Favorites option in Settings, that allows dragging the favorites around until finished (maybe indicated by user clicking on a button).

I hope some of these suggestions are useful, or maybe spark some other ideas for further features 😊

**Comment by mxmilkiib** [comment]
Just came here as I was wondering about symbols. I wanted a •.

I would suggest creating a new issue specifically about that to track that specific potential feature, but the convo is here and I'll let Tom proceed the way they wish.

**Comment by tom-james-watson** [comment]
Yeah it's better to create one issue per topic so discussion can properly be tracked. @nightgolfer, do you mind splitting these points up into multiple issues? Thanks!

**Comment by nightgolfer** [comment]
Yes of course, sorry I wasn't thinking 😅

I'll get them split ASAP 👍

**Comment by nightgolfer** [comment]
I've split the whole thing into separate issues. I did my best to preserve (or remove) context, hope everything still makes sense 👍
