### ISSUE TITLE
Unable to set binding to `<Super>e`

### ISSUE THREAD

**Issue by tomsquest** [tom-james-watson/Emote#14]
I tried binding `Super+e` and the console log show this error on startup.

I made sure to have disable Kubuntu builtin emoji shortcut bound to Meta+e beforehand.

```bash
$ emote
Launching emote daemon

** (emote:26718): WARNING **: 10:58:26.486: Binding '<Super>e' failed!
```

**Comment by tomsquest** [comment]
And by the way, do you know how to reset/edit the config ?
I don't have anything in `~/.local/share/Emote` :(

**Comment by tom-james-watson** [comment]
home under snap is `snap/<app>/current`.

You should just be able to launch emote a second time to bring up the interface again and rebind the hotkey, though.

**Comment by tom-james-watson** [comment]
home under snap is `snap/<app>/current`.

You should just be able to launch emote a second time to bring up the interface again and rebind the hotkey, though.

**Comment by tomsquest** [comment]
ah yes :+1: I just found about the user_data.db.

**Comment by widardd** [comment]
Yup, just broke it trying to bind "Super+." to mimic Windows behavior. That's a nice trap, tbh! :D

**Comment by 73** [comment]
I set it from the GNOME Keyboard shortcuts dialog. Works.

**Comment by tom-james-watson** [comment]
Yeah, not sure why this doesn't work. To be honest I unless somebody can tell me why it won't work at the moment, I'll just see if this is fixed when I rewrite the ui: https://github.com/tom-james-watson/Emote/issues/20.

**Comment by vemonet** [comment]
Note that setting it as a custom shortcut in your system directly as explained above by @balazsorban44 works well, but it comes with a small inconvenience: the Emote popup window will show up slower (cf. https://github.com/tom-james-watson/Emote/issues/54)

So to get the faster popup, the best workaround I could find at the moment is to use `Alt+E` which is quite close to `Super+E` and works fine without conflicting with other keybindings (for me at least!)
