### ISSUE TITLE
Preferences/Guides dialogs appears behind the emoji window

### ISSUE THREAD

**Issue by tomsquest** [tom-james-watson/Emote#15]
On click on Preferences, the Pref window appears behind (thus being hidden) the emoji window.

![image](https://user-images.githubusercontent.com/365778/95181970-4787d200-07c4-11eb-90ac-78e025704bf7.png)

**Comment by tom-james-watson** [comment]
What OS / desktop environment are you running (with versions)? Looks like KDE? They are created as child windows of the app window, so that shouldn't happen. Works as expected on gnome 3.34 onwards.

**Comment by tomsquest** [comment]
Yes, I am using KDE on Kubuntu 20.04.

**Comment by tom-james-watson** [comment]
Closing this out due to age. If you can confirm that this still happens on newer KDE, e.g. 22.04 onwards, then we can reopen.
