### ISSUE TITLE
Hide Emote windows given it is focused when shortcut is pressed again

### ISSUE THREAD

**Issue by tomsquest** [tom-james-watson/Emote#16]
Feature request:
Given Emote has the focus (the user has pressed the shortcut, ctrl+atl+e)
When the shortcut is pressed again
Then Emote should close itself

This would provide another way to dismiss emote using the same shortcut.
Thus the shortcut will be able to show and hide the main window.

**Comment by tom-james-watson** [comment]
Yeah would probably make sense

**Comment by tom-james-watson** [comment]
Released in 1.2.0 :smile:

**Comment by tomsquest** [comment]
Nice ! Thanks ! :1st_place_medal:
