### ISSUE TITLE
Auto copy not working for me (UK) but working for my friend (US)

### ISSUE THREAD

**Issue by purpledalek** [tom-james-watson/Emote#163]
hey, the auto paste doesn't seem to work for me (i'm in the UK) but it does for my friend (who's in the US) with the same distro (Arch with xfcee4), equally up to date and both of us downloaded Emote through aur, and i'm at a bit of a loss to know why it work for my friend but not for me. we also both have the same settings on clipboard manager

**Comment by tom-james-watson** [comment]
Probably you are using Wayland? The aur version has some changes vs this codebase though, so I'd say it's not officially supported.

**Comment by purpledalek** [comment]
i just checked and i'm definitely using X11
![image](https://github.com/user-attachments/assets/ceb7db8d-2cf7-43a2-8360-972bfc1a06de) but im gonna see if the version from this repo works

**Comment by purpledalek** [comment]
found the fix, i was missing xdotool 🤦
