### ISSUE TITLE
Wrong emoji names: U+1F38F(🎏)

### ISSUE THREAD

**Issue by yuguamax** [tom-james-watson/Emote#28]
Currently, U+1F38F(🎏) is displayed as "Flag" in Emote.
It is not a Flag. It is a koinobori.
https://en.wikipedia.org/wiki/Koinobori

**Comment by tom-james-watson** [comment]
I'm going to change this to be called "carp_streamer", which is the official emoji name - https://emojipedia.org/emoji/%F0%9F%8E%8F/. That will be released in the upcoming v2.

Searching "koinobori" should still show the emoji as it is listed as an alias.
