### ISSUE TITLE
Adding keyword: ideograph_advantage

### ISSUE THREAD

**Issue by yuguamax** [tom-james-watson/Emote#30]
https://github.com/tom-james-watson/Emote/blob/c6be700ab1af53ddd94d1935bc84e6c16fcdf931/static/emojis.json#L7444
Among Japanese speakers, this pictogram is used to mean "good value".
Suggest adding a keyword.

**Comment by tom-james-watson** [comment]
Added "bargain" and "value" as keywords. Thanks.
