### ISSUE TITLE
Adding keyword:u6709

### ISSUE THREAD

**Issue by yuguamax** [tom-james-watson/Emote#31]
https://github.com/tom-james-watson/Emote/blob/c6be700ab1af53ddd94d1935bc84e6c16fcdf931/static/emojis.json#L7375
Among Japanese speakers, this pictogram is sometimes used to mean paid or not free.
I suggest adding the keyword.

**Comment by yuguamax** [comment]
I made a mistake, it's u6709.
I'm sorry.

**Comment by tom-james-watson** [comment]
Added "paid" and "not-free" as keywords. Thanks!
