### ISSUE TITLE
transgender flag emoji

### ISSUE THREAD

**Issue by mtoal87869** [tom-james-watson/Emote#34]
Was hoping you would consider adding the new-ish transgender flag emoji. Thanks.

**Comment by tom-james-watson** [comment]
Yup, can do! 🏳️‍⚧️

At the moment though, the app can't display it when packaged as an app. It looks like this:

![image](https://user-images.githubusercontent.com/3852719/112618283-4146ea00-8e26-11eb-9775-64f45ce6aa07.png)

I'm seeing if updating the snap to core20 fixes this.

**Comment by tom-james-watson** [comment]
It doesn't look like I can update the app to core20 yet because the corresponding snap gnome extension required for core20 is still experimental: https://snapcraft.io/docs/gnome-3-38-extension.

I think we'll have to revisit this in a few months.

**Comment by eliannelavoie** [comment]
I kinda wish we had an option to enable all emoji's even if they don't display properly in the app!

I don't really care if the picker doesn't show the right thing: it works in Firefox, so I just want a quick way to type it. 
Unicode gets updated often enough that it's normal for fonts to lag behind, but that doesn't mean we should be unable to pick them in the meantime.

**Comment by tom-james-watson** [comment]
I'm not sure that's a good idea, personally. It will just make the app look broken. Potentially a toggle in the settings to see unsupported emojis, but I'd rather not over-complicate the app.

**Comment by eliannelavoie** [comment]
Yeah, that is why I wrote "I wish we had the *option*"!

**Comment by tom-james-watson** [comment]
The flag will be added to the emoji list when https://github.com/tom-james-watson/Emote/issues/47 is complete, but until https://github.com/tom-james-watson/Emote/issues/48 is done, I think we still have to hide the newest emojis in the ui as it won't render properly.

**Comment by tom-james-watson** [comment]
There's an argument for overriding that decision and displaying "broken" emojis too, but that's a question for a separate ticket.

Going to close this out because there's nothing I can do here.
