### ISSUE TITLE
install only through snap store?

### ISSUE THREAD

**Issue by twisthead** [tom-james-watson/Emote#36]
this has to be a joke. there is only a single way to install this app and that is snap store. with all that debates on the legitimacy of snap in Foss world, you chose to publish your app only on snap store. what a joke?
Please make another way to install it (even compiling the source would be okay.)
thank you very much

**Comment by tom-james-watson** [comment]
This is not the way to interact with the open source community. You can take your entitlement elsewhere. Blocked.
