### ISSUE TITLE
Keeping the app window open until user close it manually. 

### ISSUE THREAD

**Issue by rago666** [tom-james-watson/Emote#37]
Firstly, thank you for creating the best emoji app for linux. 
This feature is similar to windows emoji picker, demonstrated in [this](https://www.youtube.com/watch?v=7og_0FUYkTk&t=80s) video. This will be very intuitive for regular mouse users.

**Comment by tom-james-watson** [comment]
What exactly is the use case?

If you want to select multiple emojis, you can do that with shift-click or right click. Then either you can paste the resulting selection or automatically insert it if you select the last emoji with left click.

**Comment by tom-james-watson** [comment]
Ahh I see!

Yeah let me have a think about that at some point. Will probably be easier to make the change to test that out.

I'm not sure about refocusing search on shitft+enter. I totally get your proposal, but also I think some people like to get really excited and enter the same emoji several times 🎉 🎉 🎉 and having to search for it again each time would be annoying maybe.

**Comment by abhijit-hota** [comment]
Maybe we can implement an option for close on <kbd>Esc</kbd>.

**Comment by tom-james-watson** [comment]
Closing this out because at the moment I am happy with the current UX.

**Comment by Heus-Sueh** [comment]
I found the shortcuts totally confusing or they are not working as they should, but I think there should be a toggle to keep the app open or something like that, otherwise the app would be perfect

**Comment by Heus-Sueh** [comment]
Please implement a toggle for the window to remain open when selecting an emoji, not all users may need the window to remain open, but some do, so consider implementing this.
