### ISSUE TITLE
Tab should select the first emoji in the list

### ISSUE THREAD

**Issue by haasn** [tom-james-watson/Emote#38]
It's very surprising and unintuitive for tab to select the preference button at the top right, followed by the emoji category list, before tabbing into the actual emoji list. This breaks the intuitive flow of using tab to choose which emoji I want to insert.

I think that *only* the emoji list should be tabbable. There's already ctrl+f to choose the search bar, and ctrl+tab to choose the emoji category.

**Comment by tom-james-watson** [comment]
I don't think that would be great for accessibility. Generally, tabbing should go through UI elements in order.

If you want to use the keyboard to select emojis, you can press the down key from the search bar to focus on the first emoji, then use the direction keys to move between emojis.

**Comment by cmalard** [comment]
Hey @tom-james-watson :raising_hand_man: 
Same feeling here, just discovered your (really nice) app some days ago and this is what I'm fighting with right now.
As a dev too, I'm constantly using `<tab>` to select the first suggestion and this is not what is happening here, even if using arrows makes total sense.
Pure UX consideration, arrows is farther to reach on keyboards (have to move my arm) than tab (which I can access just by moving a finger :see_no_evil:)
![image](https://user-images.githubusercontent.com/1692136/166146341-c43815c5-f80b-4d16-8140-40ada9f8b8a4.png)
Skin tone and menu bar should not be that used, should they?

What about changing the tab order? Like putting them _after_ the emojis?

Thanks a lot for this cool work by the way ;-) :beers:
