### ISSUE TITLE
Skin tones

### ISSUE THREAD

**Issue by 8d4eg6** [tom-james-watson/Emote#39]
This is a request to add a skin tone picker for the emoji that support them.

**Comment by 8d4eg6** [comment]
(If the option is already there and I missed it :facepalm: then I'd be happy to hear that as well)

**Comment by tom-james-watson** [comment]
Yeah there's no support for skin tones at the moment. The easiest way to implement this would be a global preference, I think, but I assume people would want to be able to choose a global default and to also be able to select a one-off skin tone for individual emoji, too. I don't really have any good ideas for how the UX for selecting a skin tone would work though.

**Comment by markkrj** [comment]
@tom-james-watson I agree that selecting skin tones for one off emojis would be a nice-to-have but, being able to select a default one would suffice for most cases.

I was looking at your codebase to try and implement this, and I saw that your emojis.json file already specify which emojis can have skin tone with `fitzpatrick_scale` boolean. So, if you can add another option to settings (as with themes), and place the following characters as option, it is a matter of concatenating it to those emoji to change its skin tone.
🏻
🏼
🏽
🏾
🏿

You can try it yourself by pasting a 👍 and any of these characters (emojis) here in comments... Like:
👍
+
🏽
= 👍🏽

Just a suggestion in case you go this way, you could use those emojis to denote each option and a yellow square (🟨) to denote the `System Default` emoji in the settings... 

Take a look at my PR for [Cinnamenu](https://github.com/linuxmint/cinnamon-spices-applets/pull/3844)

**Comment by soygabimoreno** [comment]
I discovered this project a few time ago. It is amazing! It is really helpful to add emojis easily.

If we could change the skin tones that would be awesome!

I totally agree with "default one would suffice for most cases" in the previous comment.

**Comment by tom-james-watson** [comment]
You can now test this out on the edge snap channel. See https://github.com/tom-james-watson/Emote/pull/49.
