### ISSUE TITLE
All squares displayed on Manjaro

### ISSUE THREAD

**Issue by kdvcodes** [tom-james-watson/Emote#4]
I installed this on my Manjaro system, but it's displaying all squares in the application. Any way to fix this problem?

**Comment by tom-james-watson** [comment]
Do you see no emojis at all in any of the categories?

I have an open issue in the snapcraft forum asking for help with this already actually - https://forum.snapcraft.io/t/some-emojis-missing-when-running-app-in-snap/16699

**Comment by kdvcodes** [comment]
No emoji at all, squares in places of menu items (I think these are texts) as well.

**Comment by gagangulyani** [comment]
Same issue in ArcoLinux. Seems like Arch Based Distros have this issue.

**Comment by tom-james-watson** [comment]
Definitely sounds like something to do with font bundling. I'll have to reach out for some more help from upstream because I've no idea what I'm doing wrong :disappointed:

**Comment by BenElgar** [comment]
Same for me. Including a screenshot:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/3443024/92592596-bc382100-f297-11ea-9289-aba35a537375.png">

**Comment by Ozman** [comment]
Same for me on Manjaro, just empty boxes.

**Comment by tom-james-watson** [comment]
I've opened a topic on the snapcraft forums - https://forum.snapcraft.io/t/missing-fonts-on-some-distributions/19880

I see some users reporting similar issues on other snaps: https://forum.snapcraft.io/t/fonts-missing-in-chromium/15987. Are any of you running other snaps without issues?

**Comment by BenElgar** [comment]
Ah, you're right. This appears to be an issue with snap, not with Emote. I just installed another application and the fonts are broken in the context menus.

If I have time (doubtful), I might have a look at packaging emote differently to work around this (and save myself maintaining a whole new packaging system just for Emote).

**Comment by tom-james-watson** [comment]
Feel free to document that work if you do - I'm not against providing different packages, if it's not too much work.

**Comment by tom-james-watson** [comment]
FYI a potential workaround is:

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by tom-james-watson** [comment]
I'm not sure there's much I can do here and conversation seems to have died down, so I'm going to close this out for now.
