### ISSUE TITLE
Use packaged emoji font instead of system font

### ISSUE THREAD

**Issue by reitzig** [tom-james-watson/Emote#40]
I disabled (read: uninstalled) the default emoji font on my i3 Ubuntu system because I found it to be visually inconsistent and invasive for my overall UX (cf. [askubuntu#1030690](https://askubuntu.com/q/1030690/69674)). Hence, the emote picker doesn't look all that attractive:

![image](https://user-images.githubusercontent.com/4246780/119968525-e3618a80-bfad-11eb-9186-92ed3d0264b6.png)

If at all possible, please include an emoji-capable font in the snap, and use that one (as a fallback?).

**Comment by tom-james-watson** [comment]
I think that that would potentially lead to inconsistencies between the emoji in the app and the emoji once you paste it into your app, which would be unexpected, no?

**Comment by reitzig** [comment]
It's inconsistent as it is: most apps I tried _do_ show e.g. `man_shrugging` even though the font used in emote doesn't have a glyph for it, and they use different fonts for emojis. So I don't think fixing a font for the picker leads to a reduction of UX.

**Comment by tom-james-watson** [comment]
I actually don't know how to do this anyway. If somebody could shed some light on that then it might make sense.

**Comment by reitzig** [comment]
I have no experience with Python + GTK3, but [Pango Markup](https://www.chordpro.org/chordpro/pango_markup/) seems to support changing fonts. Making custom fonts known to Pango also [seems to be possible](https://stackoverflow.com/a/66177017/539599).

**Comment by tom-james-watson** [comment]
You can now test this out on the edge snap channel. See https://github.com/tom-james-watson/Emote/pull/49.

**Comment by reitzig** [comment]
Awesome, thanks! :+1:

**Comment by reitzig** [comment]
@tom-james-watson This has been reverted with 4.0.0, right? 

Don't think I minded a ~100MB snap, but I recognize that mine is probably a corner case.

Is there a workaround you're aware of or will I have to re-install an "emoji font"?

**Comment by tom-james-watson** [comment]
Yeah unfortunately this was causing more problems than it was solving. I think you just need to have an emoji font installed, I'm afraid.
