### ISSUE TITLE
Set process name/title

### ISSUE THREAD

**Issue by reitzig** [tom-james-watson/Emote#43]
When I run:

```bash
emote &
killall emote
```

I expect the program started in the first line to be killed by the second. Unfortunately, emote starts a process named `python3`.

There may be different avenues:

 - In Python, e.g. using [dvarrazzo/py-setproctitle](https://github.com/dvarrazzo/py-setproctitle).
 - Using a Bash wrapper script.
 - Maybe there's something in snap, I don't know.

**Comment by reitzig** [comment]
🧡 :pray:

**Comment by tom-james-watson** [comment]
I currently am actually unable to release an update though :confused: - https://github.com/tom-james-watson/Emote/issues/63
