### ISSUE TITLE
Add the "smiling face with tear" emoji

### ISSUE THREAD

**Issue by waldyrious** [tom-james-watson/Emote#46]
There are some emoji missing from the list, and [Smiling face with tear](https://emojipedia.org/smiling-face-with-tear/) is one of them. → 🥲

I noticed similar issues, like #34 and #19. It would be nice to have some guidance on the README about how to add new emoji, or whether that depends on upstream updates. For example, would changes like those of https://github.com/tom-james-watson/Emote/commit/f6fec5aeadb8dcb8f393d695f52844f63db65997 work generally? Are the emoji that can be added limited to a specific Unicode version? Etc.

If some pointers are provided, I'd be happy to submit a PR!

**Comment by tom-james-watson** [comment]
I'm going to close this in favour of https://github.com/tom-james-watson/Emote/issues/47, which would add all of these recent emojis.

**Comment by tom-james-watson** [comment]
Unfortunately I think this still wouldn't display properly in the app until we work out how to do https://github.com/tom-james-watson/Emote/issues/48, so I probably we have to hide the most recent emojis still.
