### ISSUE TITLE
Switch emoji data source

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/Emote#47]
Manually adding emojis to emojis.json is not scalable. I have been looking for a better source of emoji data that is actually going to be maintained. There are some that are produced from https://unicode.org/Public/emoji/13.0/emoji-test.txt, which can be seen as the source of truth, but these do not include any aliases, which makes it way less useful.

I think the best option I have found is to use the github data, as these actually include some aliases, though less than we currently have.

https://github.com/github/gemoji/blob/master/db/emoji.json

**Comment by waldyrious** [comment]
There's also the [data](https://github.com/hfg-gmuend/openmoji/blob/master/data/) directory in the https://openmoji.org repository; particularly [openmoji.csv](https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv), whose fields "annotation", "tags" and "openmoji_tags" may be useful.

From Unicode, there's the data in CLDR's "annotations" section, in both [XML](https://github.com/unicode-org/cldr/blob/d79fe89e47658b7ce30af532132cf5021449a457/common/annotations/en.xml#L1071) and [JSON](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-annotations-full/annotations/en/annotations.json#L5235-L5246) (warning: huge file) formats. The CLDR dataset is updated every 6 months or so, and even includes translations for those terms in dozens of other languages ([example](https://github.com/unicode-org/cldr/blob/d79fe89e47658b7ce30af532132cf5021449a457/common/annotations/pt.xml#L636)). What's more, [anyone can contribute](http://cldr.unicode.org/index/survey-tool/accounts) to add/improve annotations in various languages :)

Ideally, it should be possible to obtain [Emojipedia](https://emojipedia.org)'s listing of "Also Known As", "Apple Name", "Unicode Name", etc., as seen e.g. [here](https://emojipedia.org/thumbs-up/), but I don't think they make those available in a machine-readable way :(

**Comment by tom-james-watson** [comment]
Thank you - that's very useful! https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.json looks like it should have everything we need to be honest. Either that or the CSV.

**Comment by tom-james-watson** [comment]
You can now test this out on the edge snap channel. See https://github.com/tom-james-watson/Emote/pull/49.
