### ISSUE TITLE
Upgrade to core20

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/Emote#48]
We need to upgrade the app to core20 base and gnome-3-38 extension to update the fonts and therefore the list of supported emojis.

I've tried to do this on https://github.com/tom-james-watson/Emote/tree/core20 but have hit some roadblocks. The python code does / `emote` binary no longer appears to be making it into the snap and I don't understand how to fix it.

**Comment by markkrj** [comment]
@tom-james-watson maybe it's related to [this](https://forum.snapcraft.io/t/trouble-bundling-python-with-classic-confinement-in-core20-4-0-4/18234/2)?

**Comment by tom-james-watson** [comment]
I did some more work (https://github.com/tom-james-watson/Emote/tree/core-20) on this but still could not get anywhere. There seem to be various issues with bundling python using core20. I tried using pyinstaller and just bundling in the whole pre-built package but that hit its own host of issues. Time-boxing this after already spending multiple hours on it.

**Comment by tom-james-watson** [comment]
I also do not seem able to bundle the snap anymore with core-18, at least from my Ubuntu 21.10 machine. Every time I build a new snap I'm seeing lots of errors along the lines of:

```
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'version'
```

and then all of the emojis are rendering tiny. It seems to be some incompatibility between what is in the snap and what it is looking up on my machine.

**Comment by sonjoonho** [comment]
Have never used snap before; took a crack of this; almost lost my sanity.

**Comment by tom-james-watson** [comment]
Done
