### ISSUE TITLE
Thai language reported can cause repeated keystrokes

### ISSUE THREAD

**Issue by CalmDownMonkey** [tom-james-watson/Emote#50]
I'm on Ubuntu Budgie 21.04.

It works great using the US keyboard layout, but if I'm using Thai, and I pick an emoji, there will be a long delay, the emoji will be correctly pasted, then it will be stuck spamming the "v" key until you press a key to stop it and remove the extra keystrokes.

e.g. using US keyboard layout:
😁

e.g using TH keyboard layout
😁อออออออออออออออออออออออออออออออออออออออออออออ(forever)

Ctrl+V usually works fine as a keyboard shortcut in Thai so I'm not sure why it would do this.

**Comment by tom-james-watson** [comment]
Can you please check if this is still an issue on version 4.0.0? I will reopen the issue if so.
