### ISSUE TITLE
Show gendered results when searching generic/nuetral equivalents

### ISSUE THREAD

**Issue by hirusi** [tom-james-watson/Emote#51]
## How to Reproduce

1. Open Emote.
2. Search for ~~`raising`~~ `person`
3. You'll see the emoji for 'Person raising hand' but not man or woman raising hand.

## Expected

Also show man or woman emojis alongside the person emojis. This would be a convenience add.

**Comment by tom-james-watson** [comment]
Seems to work as expected to me?

![image](https://user-images.githubusercontent.com/3852719/134475614-f0bceea2-9bb8-4082-ae79-0744d3648e7c.png)

Are you using the aur build by any chance?

**Comment by hirusi** [comment]
I'm using the snap release.

Turns out I made a mistake while making this ticket (sorry!).

What I meant to make a feature request for is when `person` is written, also show man and woman emojis. The person emojis look wildly leaning towards male.

Not sure something you might consider.

**Comment by hirusi** [comment]
Or, there could be a dropdown similar to skin color that lets you select one from: Man, Woman, Person. Non-gendered emojis then get copied as gendered equivalents.

Thinking out loud, really...

**Comment by lkrms** [comment]
> Are you using the aur build by any chance?

@tom-james-watson the AUR package was still v2.0.0 until today, but I saw your question while preparing the update and tested the `raising` search out of curiosity:

![Screenshot_2021-09-23_19-55-51](https://user-images.githubusercontent.com/2563783/134513485-6068a04f-6964-48e8-aea3-d02d03f951d2.png)

After updating to 3.0.3:

![Screenshot_2021-09-23_22-53-19](https://user-images.githubusercontent.com/2563783/134513821-5252bf81-d1d6-49cc-bc0e-338832b77275.png)

**Comment by tom-james-watson** [comment]
> @tom-james-watson the AUR package was still v2.0.0 until today, but I saw your question while preparing the update and tested the raising search out of curiosity:

Yeah it was when asking that that I remembered that you were relying release notifications and so made one.

> What I meant to make a feature request for is when person is written, also show man and woman emojis. 

To be honest I think the way it works at the moment makes sense. "Person" in emojis specifically refers to gender-neutral emojis, so I'd only expect the gender-neutral ones to appear.

> Or, there could be a dropdown similar to skin color that lets you select one from: Man, Woman, Person. Non-gendered emojis then get copied as gendered equivalents.

It's a nice idea and definitely worth thinking about, but I think people mix the person/man/woman emojis quite often and so needing to switch the dropdown each time to get the emoji you want would be annoying.

**Comment by waldyrious** [comment]
> needing to switch the dropdown each time to get the emoji you want would be annoying.

Instead of a dropdown, it could be a [toggle button group](https://developer.gnome.org/hig/patterns/controls/buttons.html#toggle-buttons) (like this ![Screenshot from 2021-09-23 15-47-03](https://user-images.githubusercontent.com/478237/134529675-7a0ecac3-8652-467b-8bc4-4a7608b8ec09.png) but with 3 possible states). That way it would be a one-click operation, while still greatly reducing the amount of emoji listed in the box.

**Comment by tom-james-watson** [comment]
I'm going to close this out. I think it's a nice idea but I'm not convinced by the UX of the suggestions at this point. Thanks, guys.
