### ISSUE TITLE
Searches are sluggish until a few characters have been entered

### ISSUE THREAD

**Issue by dgunay** [tom-james-watson/Emote#55]
(Disclaimer: I'm on the AUR build)

When I open the picker and start typing, it takes a fraction of a second for each character I type to show up. Presumably this is because it blocks on updating the search bar (at least visually) until the search has finished.

The search function is probably executing for each character the user types, which starts out pretty slow:

https://github.com/tom-james-watson/Emote/blob/cfa8021e1e0a0f414d262ca6f9acc6270690ac15/emote/emojis.py#L335-L344

Some ideas:

- Wait until a few hundred milliseconds of inactivity/no typing before running search
- Use a more efficient data structure to store `all_emojis`

**Comment by tom-james-watson** [comment]
Yeah the "easy" fix is to debounce the searches. I say "easy" because compared to something like javascript, doing this is python is more difficult than it should be. I had a go a while back and struggled to get it working.
