### ISSUE TITLE
A logo icon for Emote project

### ISSUE THREAD

**Issue by Olothe1st** [tom-james-watson/Emote#6]
Hope you like it, 
![PicsArt_07-19-11 56 30](https://user-images.githubusercontent.com/68645338/88173251-2b8b8000-cc1a-11ea-9764-bd0579fdeb49.jpg)

**Comment by tom-james-watson** [comment]
Hello - thanks for your input! It's a cool concept - well done.

Maybe my original post wasn't clear enough, but check my latest comment I have left on https://opensourcedesign.net/jobs/jobs/2020-07-04-icon-needed-for-open-source-emoji-picker-emote. What we need is a square application icon that ideally follows the Gnome HIG for icons.

**Comment by Olothe1st** [comment]
Ok then let me go back to review it

**Comment by Olothe1st** [comment]
![icon](https://user-images.githubusercontent.com/68645338/88229413-9b285c00-cc68-11ea-868f-843cbd137e90.png)
How about now

**Comment by Olothe1st** [comment]
I put a white bg for you to see it clearly

**Comment by tom-james-watson** [comment]
Thank you very much for your contribution - it's very much appreciated.

I think it's not quite the right fit for the project, so I'll see what else is suggested by other contributors.

Some concrete feedback: it's still not following all of the gnome guidelines - there's detail that is tool fine, it shouldn't have a background and it shouldn't have text. I'm not personally a big fan of the icon itself either, unfortunately.

**Comment by tom-james-watson** [comment]
Yeah that's awesome - keep it up!
