### ISSUE TITLE
Skin tone isn't configurable for some `people-body` emojis

### ISSUE THREAD

**Issue by masonmcelvain** [tom-james-watson/Emote#60]
## Problem
When I select a skin tone, I expect all people/body emojis to change to that skin tone. Instead, I see that certain (seemingly random) people/body emojis still have the default skin tone.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/52104630/148160209-6c5dfef1-e654-4146-8b9e-f75589502f6e.png)

![image](https://user-images.githubusercontent.com/52104630/148160193-0347bf84-f24c-4312-916b-2ec1d1af956e.png)
</details>

The README states
> Emoji data is sourced from https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.csv which is compiled by the lovely people at https://openmoji.org.

But I see that https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.csv seems to have all the skin tones for all the people/body emojis.

<details>
<summary>For example, here is the `hand-fingers-open` data from the csv.</summary>

![image](https://user-images.githubusercontent.com/52104630/148160499-e9858908-55a0-4753-b442-b072e0b12cae.png)
</details>

## Environment
I'm using the snap distribution on Ubuntu 21.10, GNOME 40.4.0 with Wayland
```
⚡ snap list emote
Name   Version  Rev  Tracking       Publisher         Notes
emote  3.0.3    19   latest/stable  tom-james-watson  -
```

**Comment by masonmcelvain** [comment]
Came back to this and found #52 and #48 - making this issue a bit of a duplicate. Thanks for the great project!

**Comment by tom-james-watson** [comment]
Yup that's right. Thanks!
