### ISSUE TITLE
[Debian] Apparmor errors

### ISSUE THREAD

**Issue by udev** [tom-james-watson/Emote#61]
Thanks for the great project!

I've been trying to get this working on Debian following directions from the Snap store:
https://snapcraft.io/install/emote/debian#install

Under the hood it seems like there is no apparmor profile installed along with the package so I'm running into runtime permissions and other errors due to apparmor denying requests. That looks something like this:
```
Jan  7 14:16:22 steam kernel: [ 2356.065131] audit: type=1400 audit(1641586582.426:217): apparmor="DENIED" operation="open" profile="/usr/bin/snap" name="/sys/kernel/mm/transparent_hugepage/hpage_pmd_size" pid=10750 comm="emote" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jan  7 14:16:22 steam kernel: [ 2356.067778] audit: type=1400 audit(1641586582.430:218): apparmor="DENIED" operation="open" profile="/usr/bin/snap" name="/proc/version" pid=10750 comm="emote" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jan  7 14:16:22 steam kernel: [ 2356.073432] audit: type=1400 audit(1641586582.434:219): apparmor="DENIED" operation="open" profile="/usr/bin/snap" name="/proc/cmdline" pid=10750 comm="emote" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jan  7 14:16:22 steam kernel: [ 2356.073477] audit: type=1400 audit(1641586582.434:220): apparmor="DENIED" operation="open" profile="/usr/bin/snap" name="/snap/core/11993/usr/lib/snapd/info" pid=10750 comm="emote" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
I've been fooling around with [creating an apparmor profile](https://gitlab.com/apparmor/apparmor/-/wikis/Profiling_with_tools) but it seems like too much additional work and doesn't solve the problem. I've got emote running at least but when I choose an emoji it never appears at the cursor :(

**Comment by tom-james-watson** [comment]
I don't know much about apparmor or how it would interact with emote or snaps. Unless you think there is something that specifically needs changing in emote then I think I'd just have to close this out as it seems like it is likely a machine configuration issue. You can try asking for help on the [snapcraft forums](forum.snapcraft.io), maybe?

**Comment by udev** [comment]
Thanks. I'll try there. Everything I've found so far seems to indicate that apparmor config should be prepackaged so maybe it's something to bring up over at debian.org as well.

**Comment by jeremyckahn** [comment]
I started experiencing this issue randomly after having Emote installed and working on my Ubuntu 22.04 environment. I think it may have been related to a system or other package update. I was able to resolve it by reinstalling Emote.

@tom-james-watson btw thank you for the excellent program! I use it all the time. 🙂
