### ISSUE TITLE
When active window is a Terminal use Ctrl-Shift-V to paste, not Ctrl-V

### ISSUE THREAD

**Issue by rbreaves** [tom-james-watson/Emote#66]
I know this will be most helpful for x11 initially but here is a list of wm_class names you can use for the terminal app grouping.

Be sure to make things case insensitive.

"alacritty","cutefish-terminal","deepin-terminal","eterm","gnome-terminal","guake","hyper","io.elementary.terminal","kitty","konsole","lxterminal","mate-terminal","qterminal","st","sakura","station","tabby","terminator","termite","tilda","tilix","urxvt","xfce4-terminal","xterm"

**Comment by reitzig** [comment]
Same as #44 ?

**Comment by tom-james-watson** [comment]
Closing as duplicate of https://github.com/tom-james-watson/Emote/issues/44
