### ISSUE TITLE
can I use a different font?

### ISSUE THREAD

**Issue by Hichen220** [tom-james-watson/Emote#67]
I currently have the Apple Color Emoji as my default font, but emojis in the app still use the Google Noto emojis, how can I use the Apple font?

**Comment by ElMaxonDSCRD** [comment]
Same issue here, would like to use the twitter font (which is already installed on my Arch system and works fine ; emote just uses another font for some reason)

**Comment by wezm** [comment]
If you comment out these lines it will use your system emoji font:

https://github.com/tom-james-watson/Emote/blob/f71e41b92bfe8a32451f0f0d93ae47da886d2b51/emote/__init__.py#L12-L15

I've done that in a customised PKGBUILD for Arch: https://github.com/wezm/aur/commit/7f101026d5fab20095f31a1f1b5c6dc34bdbde84

**Comment by Hichen220** [comment]
> If you comment out these lines it will use your system emoji font:
> 
> https://github.com/tom-james-watson/Emote/blob/f71e41b92bfe8a32451f0f0d93ae47da886d2b51/emote/__init__.py#L12-L15
> 
> I've done that in a customised PKGBUILD for Arch: [wezm/aur@7f10102](https://github.com/wezm/aur/commit/7f101026d5fab20095f31a1f1b5c6dc34bdbde84)

do I have to build it from scratch? If not, where could I find the file?

**Comment by tom-james-watson** [comment]
Fonts are no longer bundled into the app, so this should be fixed.

**Comment by savonbeldi** [comment]
@tom-james-watson I installed the apple color emoji using this guide: https://gist.github.com/win0err/9d8c7f0feabdfe8a4c9787b02c79ac51. How do I make Emote use this font? GNOME Characters does show me the Apple emoji's. Emote however does not.

**Comment by faizul726** [comment]
> Fonts are no longer bundled into the app, so this should be fixed.

@tom-james-watson  it's not, i built from scratch, have only one emoji font installed its still using noto emoji somehow
