### ISSUE TITLE
Wayland workaround: Add copy functionality

### ISSUE THREAD

**Issue by LostKatana** [tom-james-watson/Emote#68]
As in wayland we cannot insert the icon directly into the desired app it would be a great thing to have a copy functionality.
This could be done by right clicking the icon.

**Comment by tom-james-watson** [comment]
That should already be how it works in Wayland - left clicking an emoji should copy it to your clipboard and close the app. Right clicking an emoji lets you add multiple emojis at once to your clipboard.
