### ISSUE TITLE
Show code for emojis

### ISSUE THREAD

**Issue by Akronix** [tom-james-watson/Emote#7]
Hey!

Could we add the github / slack short code anyhow to this awesome app?

For instance, let's say that you want to know the code for this emoji: 😊 If you [go to emojipedia](https://emojipedia.org/smiling-face-with-smiling-eyes/) you get:  `:blush:` Can we add this code to the app? Maybe when the mouse pointer is over the emoji?

**Comment by tom-james-watson** [comment]
Yeah that's totally doable - the json we're loading the emojis from already has those codes as the keys. Would just need to look into how to add a tooltip on hover.

**Comment by tom-james-watson** [comment]
Hello - I've now added this and pushed a new version, though not to the stable branch yet.

Would you mind testing out the `candidate` branch of the snap to check that this works as expected for you?

You can do that with the following:


```
sudo snap remove emote
sudo snap install emote --candidate
```

**Comment by Akronix** [comment]
Cool! It works!! Although, I'd expect the codes to be between colons (`:`) so it's clear they refer to the so-called codes.

**Comment by tom-james-watson** [comment]
I think that might be a bit confusing. This isn't just a reference for what the code is on other applications where you can reference the emoji by `:text:` - this also functions as a useful description of what the emoji is.

**Comment by tom-james-watson** [comment]
Just released to stable!
