### ISSUE TITLE
[Bug] Some characters are displayed in text style instead of emoji style

### ISSUE THREAD

**Issue by ghost** [tom-james-watson/Emote#71]
Some emoji characters have a emoji style and a text style. These characters can be switched with or without the variant selector.

For example, typing `:copyright:` in emote will output `U+3299`. However, this is a bug. Correctly, `U+3299 U+FEFF` should be output.

**Comment by carbongreat13** [comment]
List of characters affected by this bug

☺☹☠❣❤🕳🗨🗯👁️‍🗨️👁🗣🐿🕊🕷🕸🏵☘🌶🍽🎗🎟⛸♠♥♦♣♟🗺🏔⛰🏕🏖🏜🏝🏞🏟🏛🏘🏚⛩🏙♨🏎🏍🛣🛤🛢🛳⛴🛥✈🛩🛰🛎⏱⏲🕰🌡☀☁⛈🌤🌥🌦🌧🌨🌩🌪🌫🌬☂⛱❄☃☄🕶🛍⛑🎛🎙🎚🎛☎🖥🖨⌨🖱🖲🎞🕯🗞🏷✉🗳✏✒🖋🖊🖌🖍🗂🗒🗓🖇✂🗃🗄🗑🗝⛏⚒🛠🗡⚔🛡⚙🗜⚖⛓⚗🛏🛋⚰⚱⚠☢☣⬆↗➡↘⬇↙⬅↖↕↔↩↪⤴⤵⚛🕉✡☸☯✝☦☪☮▶⏭⏯◀⏮⏸⏹⏺⏏♀♂⚧✖♾‼⁉〰⚕♻⚜☑✔〽✳✴❇©®™🅰🅱ℹⓂ🅾🅿🈂🈷㊗㊙◼◻🏳

**Comment by carbongreat13** [comment]
Alternatively, it would be nice to be able to change from the settings whether the text style is preferred or the pictogram style is preferred.

**Comment by tom-james-watson** [comment]
I don't see this on my machine. All of those correctly display as emojis, not unicode text.

**Comment by waldyrious** [comment]
@carbongreat13 is what you're seeing similar to [this](https://github.com/tom-james-watson/Emote/pull/49#issuecomment-907250134)? Or is the issue only in the output produced by Emote, rather than in its UI?

**Comment by carbongreat13** [comment]
> @carbongreat13 is what you're seeing similar to [this](https://github.com/tom-james-watson/Emote/pull/49#issuecomment-907250134)? Or is the issue only in the output produced by Emote, rather than in its UI?

It is not a user interface issue. It is an output issue.

**Comment by carbongreat13** [comment]
> I don't see this on my machine. All of those correctly display as emojis, not unicode text.

I would like you to paste that text below, select "ユニバーサル文字名(3)(例:\u{106B27})" and run it.
What is the output?

**Comment by carbongreat13** [comment]
See also: https://747.github.io/vsselector/#!/en-us/

**Comment by tom-james-watson** [comment]
> I would like you to paste that text below, select "ユニバーサル文字名(3)(例:\u{106B27})" and run it.
What is the output?

I don't know what you mean - what do you mean by "run it"?

**Comment by carbongreat13** [comment]
> > I would like you to paste that text below, select "ユニバーサル文字名(3)(例:\u{106B27})" and run it.
> > What is the output?
> 
> I don't know what you mean - what do you mean by "run it"?

Ummm, some Unicode pictograms have a emoji style and a text style.
You can choose not to specify the emoji style and text style without appending a variation selector, or you can add a [variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) to specify them.

I believe that Emote should add a variation selector to clearly indicate that it is a emoji style.
However, Emote currently does not have a variation selector.

https://747.github.io/vsselector/#!/en-us/263a

**Comment by tom-james-watson** [comment]
Do you still see this with version 4.0.0?
