### ISSUE TITLE
Merge into GNOME as default emoji picked?

### ISSUE THREAD

**Issue by adhadse** [tom-james-watson/Emote#78]
I agree the default emoji picker on GNOME sucks. And this is way more better than what gnome ships by default. I don't think user should be required to search for a better alternative and the default should be buttery smooth.

So, Do you plan to merge this into GNOME at some point? Why/ Why not?

**Comment by tom-james-watson** [comment]
That's not for me to decide. IMO there are a lot of things that would need to be addressed before that would be possible anyway. Closing this out as there's nothing to do here.
