### ISSUE TITLE
Add close, minimise and maximise in the window

### ISSUE THREAD

**Issue by mdhishamsayed** [tom-james-watson/Emote#79]
I see no close,minimise and maximise it is useful
![emote](https://user-images.githubusercontent.com/95240865/185194198-5c1fc36a-e73f-462a-9088-4c3c5d455955.png)

**Comment by tom-james-watson** [comment]
The emote popup is a modal window and so the concept of minimize, maximize or close don't make sense.

Clicking outside the window closes the window.
