### ISSUE TITLE
Request: Unicode symbol search

### ISSUE THREAD

**Issue by Alex-Vasile** [tom-james-watson/Emote#80]
Being able to search for other unicode symbols in the same place would be a great option to have.

E.g. I type "em" and one of the options that comes up is the em dash "—".

**Comment by tom-james-watson** [comment]
I think this falls under the same answer as what I gave to the request for kaomoji support - https://github.com/tom-james-watson/Emote/issues/70, I'm afraid.

**Comment by Alex-Vasile** [comment]
> I think this falls under the same answer as what I gave to the request for kaomoji support - #70, I'm afraid.

No worries. But to clarify, the linked issue seems to have two distinct replies:
1. Such a feature would not be added since it would make the software more complicated
2. You are free to fork and open a PR with changes.

Would you accept a PR for this change?

**Comment by tom-james-watson** [comment]
No I wouldn't accept a PR for this to be honest. Obviously you're free to fork and make your own version though, if you wanted to :)
