### ISSUE TITLE
Emoji is pasted into always-on-top/sticky window or just nowhere

### ISSUE THREAD

**Issue by NicolasGoeddel** [tom-james-watson/Emote#85]
I often have some sticky windows open, e.g. the Zoom chat window. But when a different non-sticky window has the focus and I bring Emote up using CTRL+ALT+E, it pastes the emoji into the Zoom chat instead of the previously focused window. Sometimes the emoji even is not pasted anywhere.

## Versions
Ubuntu: 22.04.1 LTS
gnome-shell: 42.5 
emote: 3.0.3

**Comment by tom-james-watson** [comment]
Not much that can be done about this. Emote simply pastes the emoji via simulating a ctrl+v after a small delay after the window closes. So if you have a sticky window then that's what will steal focus.

On Wayland the auto-paste is not technically possible at all, so unfortunately it's actually basically deprecated functionality anyway.
