### ISSUE TITLE
Some emoji are shown in text style in the UI

### ISSUE THREAD

**Issue by waldyrious** [tom-james-watson/Emote#86]
I originally reported this [here](https://github.com/tom-james-watson/Emote/pull/49#issuecomment-907250134). Copying the screenshot for convenience:

![Screenshot from 2021-08-27 15-30-57](https://user-images.githubusercontent.com/478237/131144021-258497aa-1712-4dc3-9d26-4bae2f1a15b0.png)

Note that this is different from #71 — as [clarified](https://github.com/tom-james-watson/Emote/issues/71#issuecomment-1143199423) by @carbongreat13, the problem there one that about the _output_ of Emote is shown in text style, rather than what's shown in the interface, whereas in my case it's the opposite. (That said, it's possible that the causes are related.)

Since my problem was not reproducible by the maintainer, I didn't report it as a separate issue. I'm doing so now because I finally found the cause: It's because I had the [ttf-unifont](https://packages.ubuntu.com/focal/ttf-unifont) package installed. After uninstalling it, Emote no longer shows these characters as text in the UI! I installed [fonts-symbola](https://packages.ubuntu.com/focal/fonts-symbola) instead, which did provide the rare characters I needed (in my case, it was 🞂 (U+1F782), which I had set as a the [prompt marker in my Starship configuration](https://starship.rs/config/#character)), without interfering with Emote. So hopefully this may help others who may find themselves the same situation.

The other reason I am reporting this is that I actually believe this to be a bug in Emote, since the emoji that showed in text style in Emote's interface were actually shown correctly (in emoji display mode) in the apps where Emote would past them to. So I suspect that somehow Emote is erroneously giving higher precedence to Unifont, even though there are local fonts that provide the characters as emoji, and in a way that doesn't happen with other fonts like Symbola.

I don't know what strategy the other apps are using to correctly identify which font to use for the emoji characters, but whatever is their system, Emote should probably try to implement something similar.

**Comment by veloute** [comment]
Experiencing the same issue.

**Comment by waldyrious** [comment]
@veloute do you have a similar setup as what I described above?

> I finally found the cause: It's because I had the [ttf-unifont](https://packages.ubuntu.com/focal/ttf-unifont) package installed. After uninstalling it, Emote no longer shows these characters as text in the UI! I installed [fonts-symbola](https://packages.ubuntu.com/focal/fonts-symbola) instead, which did provide the rare characters I needed [...], without interfering with Emote.

**Comment by tom-james-watson** [comment]
There is a new major version of emote that touches a lot of code related to this. Will close this out for now. If you still see this issue, please drop a comment. Also, please check whether you also see the same issue on the new flatpak distribution (see README). Thanks!
