### ISSUE TITLE
Window size doesn't fit contents

### ISSUE THREAD

**Issue by AdrianSingfield** [tom-james-watson/Emote#97]
My window is too small to show all 10 emoji in the row. Only 9 are shown and I always have to scroll to the side to see the others. Unfortunately the window can't be resized.
I'm on Kubuntu 23.04, using Wayland, with 200% scaling on a 2880x1800 laptop monitor.

**Comment by tom-james-watson** [comment]
Can you please share a screenshot of what you're seeing?

**Comment by tom-james-watson** [comment]
Also, if you scroll through the different emoji category pages, does it happen on all pages? Are there some emojis that render wider than others, for example rendering as two separate symbols?

**Comment by AdrianSingfield** [comment]
![Screenshot_20230601_161053](https://github.com/tom-james-watson/Emote/assets/33349908/70a03452-bb63-4239-9f12-e4b9b2c7f694)

I looked at all the pages and it's the same for all of them.

Can't tell how the dialogue size is set but a quick look into picker.py tells me that you always set grid_size and emojis_per_row to 10. I guess in that case the dialogue should be sized to accomodate this?

**Comment by tom-james-watson** [comment]
Can you please update Emote and check if this is still happening? We have just released a new major version. Thanks!

If you still see it, presuming you are using the snap version, can you please go to the preferences and try changing the theme to adwaita and see if you still see the issue?

**Comment by tom-james-watson** [comment]
Will reopen if reported as still happening on 4.0.0.

**Comment by AdrianSingfield** [comment]
I just tested and now it works as expected with all themes except the Materia-* ones (those have some weird spacing). Good enough for me! Thank you!
